
name: 'jaffle_models'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70471823455971

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  jaffle_models:
    staging:
      +materialized: view
      +schema: jaffle_intermediate
    marts:
      +materialized: table
      +schema: jaffle_marts

